In [1]:
# Python calls matrices lists, Numpy calls them arrays and Tensorflow calls them tensors.

In [2]:
import numpy as np

In [3]:
one_dimensional_array = np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [4]:
two_dimensional_array = np.array([[6,5],[11,7],[4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [5]:
sequence_of_integers = np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [6]:
random_integers_between_50_and_100 = np.random.randint(low = 50,high = 101 , size = (6,))
print(random_integers_between_50_and_100)

[88 89 76 52 67 56]


In [7]:
random_floats_between_0_and_1 = np.random.random((6,))
print(random_floats_between_0_and_1)

[0.42410031 0.74464408 0.22916278 0.89682315 0.35840243 0.31636678]


In [8]:
# Numpy uses a trick called braodcasting to virtuallly expand the smaller operand to dimensions compatible for linear algebra.

In [9]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.42410031 2.74464408 2.22916278 2.89682315 2.35840243 2.31636678]


In [10]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[264 267 228 156 201 168]


### Task 1 : Create a linear dataset

In [12]:
label = 3*6 + 4

In [13]:
print(label)

22


In [14]:
feature = np.arange(6,21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [15]:
label = 3*feature + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


### Task 2 : Add some noise to the dataset

In [18]:
noise = (np.random.random([15])*4)-2
print(noise)

[-0.56833218 -1.9781209   0.03131242 -1.84343548 -1.80463745  0.51881113
  0.12999726 -0.28924633  0.23765414  0.45928223  0.70341481  1.51825551
 -1.90598952 -1.06208226 -1.02002802]


In [19]:
label = label + noise
print(label)

[21.43166782 23.0218791  28.03131242 29.15656452 32.19536255 37.51881113
 40.12999726 42.71075367 46.23765414 49.45928223 52.70341481 56.51825551
 56.09401048 59.93791774 62.97997198]
