In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1.2,2.4,3.5,6.1,7.2,8.3,0.5])
print(one_dimensional_array)

[1.2 2.4 3.5 6.1 7.2 8.3 0.5]


In [3]:
one_dimensional_array.ndim

1

In [4]:
one_dimensional_array.shape

(7,)

In [5]:
one_dimensional_array.size

7

In [7]:
two_dimensional_array = np.array([[6,5] , [11,7] , [4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [8]:
two_dimensional_array.ndim

2

In [11]:
h = np.zeros([0,0])
h

array([], shape=(0, 0), dtype=float64)

In [12]:
g = np.ones([1,1])
g

array([[1.]])

In [13]:
sequence_of_integers = np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [14]:
random_integers_between_50_and_100 = np.random.randint(low = 50 , high = 101 , size = (6,))
print(random_integers_between_50_and_100)

[51 92 55 82 66 90]


In [15]:
random_floats_between_0_and_1 = np.random.random((6,))
print(random_floats_between_0_and_1)

[0.4678297  0.09501684 0.04875335 0.41843372 0.82034102 0.29295606]


#### Broadcasting

In [16]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.4678297  2.09501684 2.04875335 2.41843372 2.82034102 2.29295606]


#### Task 1 : Create a Linear Dataset

In [27]:
feature = np.arange(6,21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
label = 3*feature + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [29]:
len(label)

15

In [38]:
noise = (np.random.random([15]) * 4) -2
print(noise)

[ 1.58208047  0.14587825 -0.86052639 -1.02024649 -0.26931234  0.54991015
  1.94636876  0.19947329  1.58422103 -1.92099132 -0.59292081 -1.34271641
 -0.75493379 -0.11925723  1.44393138]


In [40]:
label = label + noise
print(label)

[23.58208047 25.14587825 27.13947361 29.97975351 33.73068766 37.54991015
 41.94636876 43.19947329 47.58422103 47.07900868 51.40707919 53.65728359
 57.24506621 60.88074277 65.44393138]
