In [1]:
print("Hello World!")

Hello World!


In [2]:
Numbers = [1,2,3,4,5]

In [3]:
number_squ = []
for i in Numbers:
    number_squ.append(i**2)
print(number_squ)

[1, 4, 9, 16, 25]


## Numpy - Numerical Python

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr**2

array([ 1,  4,  9, 16, 25])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr+10

array([11, 12, 13, 14, 15])

In [11]:
arr*2

array([ 2,  4,  6,  8, 10])

In [12]:
len(arr)

5

In [13]:
arr.ndim

1

In [14]:
arr.shape

(5,)

In [15]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [16]:
m1 = np.arange(20,39,2)
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [17]:
m1[0] , m1[7]

(20, 34)

In [18]:
m1[-2]

36

In [20]:
m1[[2,3,6,-1]]

array([24, 26, 32, 38])

### Slicing

In [21]:
m1[1:4]

array([22, 24, 26])

In [22]:
m1[-5:-1]

array([30, 32, 34, 36])

In [24]:
m1[::-1] # Reversing the order of the array

array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20])

### Masking

#### Boolean Indexing

In [25]:
m1 + 10

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [26]:
mask = m1<30

In [27]:
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [28]:
m1[mask]

array([20, 22, 24, 26, 28])

In [29]:
mask.astype('int')

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [30]:
m1[m1>30]

array([32, 34, 36, 38])

In [31]:
m2 = np.random.randint(1,20,10)
m2

array([ 6,  4,  9,  3, 13, 11,  2, 18,  2, 19])

In [32]:
m2[m2%2 == 0]

array([ 6,  4,  2, 18,  2])

In [33]:
a = np.array([1,4,6])
b = np.array([3,5,8])

In [34]:
a

array([1, 4, 6])

In [35]:
b

array([3, 5, 8])

In [36]:
a+b

array([ 4,  9, 14])

In [37]:
np.max(a)

6

In [38]:
np.min(a)

1

In [39]:
np.average(a)

3.6666666666666665

In [41]:
mat = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
mat.ndim

2

In [43]:
mat.shape

(3, 3)

In [44]:
len(mat)

3

In [46]:
mat.size # how many elements

9

In [47]:
np.sum(mat)

45

In [48]:
mat.sum()

45

## Net Promoter Score (NPS) Case Study

In [49]:
scores = np.loadtxt('survey.txt' , dtype = 'int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [50]:
scores.ndim

1

In [51]:
scores.size

1167

In [52]:
scores.shape

(1167,)

In [53]:
scores.min()

1

In [54]:
scores.max()

10

In [56]:
promoters = scores[scores >= 9]
len(promoters)

609

In [57]:
detractors = scores[scores <= 6]
len(detractors)

332

In [58]:
NPS = (len(promoters) - len(detractors))/scores.size * 100
NPS

23.736075407026565

In [59]:
round(NPS,1)

23.7

In [60]:
round(NPS)

24

##### Not very good NPS value