In [1]:
print("Hello World")

Hello World


In [2]:
Numbers = [1,2,3,4,5]

In [3]:
number_squ = []
for i in Numbers:
    number_squ.append(i**2)
print(number_squ)

[1, 4, 9, 16, 25]


# Numpy - Numerical python

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr**2

array([ 1,  4,  9, 16, 25])

In [9]:
arr +  10

array([11, 12, 13, 14, 15])

In [10]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [11]:
len(arr)

5

In [12]:
arr.ndim

1

In [13]:
arr.shape # it gives the tuple with 1 element i.e (5,)

(5,)

In [14]:
# numpy array should be homogeneous

In [15]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [16]:
m1 = np.arange(20,39,2)
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [17]:
m1[0]

20

In [18]:
m1[7]

34

In [19]:
m1[-2]

36

In [20]:
m1[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [ ]:
m1[[2,3,6,-1]]

array([24, 26, 32, 38])

## Slicing

In [ ]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
m1[1:4]

array([22, 24, 26])

In [ ]:
m1[-5:-1]

array([30, 32, 34, 36])

In [ ]:
m1[::-1] # reversing the order of the array

array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20])

## Masking
### Boolean Indexing

In [ ]:
m1 + 10

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
mask = m1 < 30
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1[mask]

array([20, 22, 24, 26, 28])

In [ ]:
mask.astype('int')

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [ ]:
m1[m1>30]

array([32, 34, 36, 38])

In [ ]:
m2 = np.random.randint(1,20,10)
m2

array([12,  3,  2,  2, 15, 18, 13,  4, 17,  1])

In [ ]:
m2[m2%2 == 0]

array([12,  2,  2, 18,  4])

In [ ]:
a = np.array([1,4,6])
b = np.array([3,5,8])

In [ ]:
a

array([1, 4, 6])

In [ ]:
b

array([3, 5, 8])

In [ ]:
a+b

array([ 4,  9, 14])

In [ ]:
np.max(a)

6

In [ ]:
np.min(a)

1

In [ ]:
np.average(a)

3.6666666666666665

In [ ]:
[[1,2,3],[4,5,6],[7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat.ndim

2

In [ ]:
mat.shape

(3, 3)

In [ ]:
len(mat)

3

In [ ]:
# how many elements
mat.size

9

In [ ]:
mat.sum()

45

In [ ]:
np.sum(mat)

45

## NPS Case Study
### Net Promoter Score

In [49]:
scores = np.loadtxt('survey.txt' , dtype='int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [50]:
scores.size

1167

In [51]:
scores.min()

1

In [52]:
scores.max()

10

In [53]:
promoters = scores[scores >= 9]
len(promoters)

609

In [54]:
detractors = scores[scores <= 6]
len(detractors)

332

In [55]:
NPS = (len(promoters) - len(detractors))/scores.size * 100
NPS

23.736075407026565

In [57]:
round(NPS , 1)

23.7

In [58]:
round(NPS)

24

#### Not very good NPS value