In [2]:
print("Hello World")

Hello World


In [3]:
Numbers = [1,2,3,4,5]

In [4]:
number_squ = []
for i in Numbers:
    number_squ.append(i**2)
print(number_squ)

[1, 4, 9, 16, 25]


# Numpy - Numerical python

In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr**2

array([ 1,  4,  9, 16, 25])

In [10]:
arr +  10

array([11, 12, 13, 14, 15])

In [11]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [12]:
len(arr)

5

In [13]:
arr.ndim

1

In [14]:
arr.shape # it gives the tuple with 1 element i.e (5,)

(5,)

In [15]:
# numpy array should be homogeneous

In [16]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [24]:
m1 = np.arange(20,39,2)
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [25]:
m1[0]

20

In [26]:
m1[7]

34

In [27]:
m1[-2]

36

In [28]:
m1[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [30]:
m1[[2,3,6,-1]]

array([24, 26, 32, 38])

## Slicing

In [31]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [32]:
m1[1:4]

array([22, 24, 26])

In [34]:
m1[-5:-1]

array([30, 32, 34, 36])

In [35]:
m1[::-1] # reversing the order of the array

array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20])

## Masking
### Boolean Indexing

In [36]:
m1 + 10

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [37]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [39]:
mask = m1 < 30
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [40]:
m1[mask]

array([20, 22, 24, 26, 28])

In [41]:
mask.astype('int')

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [42]:
m1[m1>30]

array([32, 34, 36, 38])

In [44]:
m2 = np.random.randint(1,20,10)
m2

array([12,  3,  2,  2, 15, 18, 13,  4, 17,  1])

In [45]:
m2[m2%2 == 0]

array([12,  2,  2, 18,  4])

In [47]:
a = np.array([1,4,6])
b = np.array([3,5,8])

In [48]:
a

array([1, 4, 6])

In [49]:
b

array([3, 5, 8])

In [50]:
a+b

array([ 4,  9, 14])

In [51]:
np.max(a)

6

In [52]:
np.min(a)

1

In [53]:
np.average(a)

3.6666666666666665

In [58]:
[[1,2,3],[4,5,6],[7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [60]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
mat.ndim

2

In [63]:
mat.shape

(3, 3)

In [64]:
len(mat)

3

In [66]:
# how many elements
mat.size

9

In [67]:
mat.sum()

45

In [68]:
np.sum(mat)

45