In [1]:
import numpy as np
import pandas as pd

#### Creating a DataFrame

In [5]:
my_data = np.array([[0,3],[10,7],[20,9],[30,14],[40,15]])
my_column_names = ['temperature','activity']
my_dataframe = pd.DataFrame(data = my_data , columns = my_column_names)
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


#### Adding a new column to a Dataframe

In [7]:
my_dataframe["adjusted"] = my_dataframe["activity"] + 2
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


#### Specifying a subset of a dataframe

In [8]:
print(my_dataframe.head(3),'\n')

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 



In [10]:
print(my_dataframe.iloc[[2]],'\n') # row 2

   temperature  activity  adjusted
2           20         9        11 



In [11]:
print(my_dataframe[1:4],'\n')

   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 



In [12]:
print(my_dataframe['temperature'])

0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32


#### Task 1 : Create a Dataframe

In [14]:
data = np.random.randint(low = 0 , high = 101 , size = (3,4))
print(data)

[[71 29 17 92]
 [22 56 86  6]
 [30 93 55 59]]


In [15]:
col = ['Eleanor' , 'Chidi' , 'Tahani' , 'Jason']
print(col)

['Eleanor', 'Chidi', 'Tahani', 'Jason']


In [16]:
dataframe = pd.DataFrame(data = data , columns = col)
print(dataframe)

   Eleanor  Chidi  Tahani  Jason
0       71     29      17     92
1       22     56      86      6
2       30     93      55     59


In [22]:
print(dataframe.iloc[1]['Eleanor'])

22


In [25]:
print(dataframe['Eleanor'][1])

22


In [23]:
dataframe['Janet'] = dataframe['Tahani'] + dataframe['Jason']

In [24]:
print(dataframe)

   Eleanor  Chidi  Tahani  Jason  Janet
0       71     29      17     92    109
1       22     56      86      6     92
2       30     93      55     59    114


#### Copying a dataframe

- Two different ways to duplicate a dataframe: 
1) Referencing
2) Copying

In [27]:
reference_to_df = dataframe
print(reference_to_df)

   Eleanor  Chidi  Tahani  Jason  Janet
0       71     29      17     92    109
1       22     56      86      6     92
2       30     93      55     59    114


In [28]:
print(dataframe['Jason'][1])

6


In [29]:
print(reference_to_df['Jason'][1])

6


In [30]:
dataframe.at[1,'Jason'] = dataframe['Jason'][1] + 5
print(dataframe['Jason'][1])

11


In [31]:
print(reference_to_df['Jason'][1])

11


In [32]:
copy_of_my_dataframe = my_dataframe.copy()

In [33]:
print(my_dataframe['activity'][1])

7


In [35]:
print(copy_of_my_dataframe['activity'][1])

7


In [36]:
my_dataframe.at[1,'activity'] = my_dataframe['activity'][1] + 3

In [37]:
print(my_dataframe['activity'][1])

10


In [38]:
print(copy_of_my_dataframe['activity'][1])

7
